### ISSUE TITLE
Have only one main CMakeList.txt file for all binaries (including tests)

### ISSUE THREAD

**Issue by catageek** [project-trillek-archive/trillek-client-core#16]
Unit tests require some compilation units to be built, and such to be configured manually in the CMakeLists.txt in tests folder. Including recursively src/ will define 2 "main" function, so each folder must be included individually.

Moreover all the settings of the main CMakeList must be applied to the tests and must be copied/pasted, with potential errors.

I propose to have only one CMakelist file for all the project to make sure that unit tests are build in the same environment as other builds.

**Comment by adam4813** [comment]
This leads to an issue were not everyone will want/need to build tests, but I suppose that could be overcome by guarding out tests with a property.

**Comment by adam4813** [comment]
I will leave issue #11 open until we have a chance to discuss this at the next meeting, or via further discussion on here.

**Comment by adam4813** [comment]
Seems this can be closed now.
