### ISSUE TITLE
One should not heap-allocate exceptions and throw pointers to them

### ISSUE THREAD

**Issue by milesrout** [project-trillek-archive/trillek-client-core#43]
https://github.com/trillek-team/trillek-client-core/blob/develop/include/bitmap.hpp#L174

One should merely throw the exception.

**Comment by catageek** [comment]
Already removed in feature_oxygen.

Thanks

**Comment by milesrout** [comment]
feature_oxygen?

**Comment by milesrout** [comment]
Reopened because it's not merged.

**Comment by catageek** [comment]
Fixed in trillek-common, commit 387c5083
