### ISSUE TITLE
The coding style looks like something out of the 1990s

### ISSUE THREAD

**Issue by milesrout** [project-trillek-archive/trillek-client-core#44]

**Comment by Ratstail91** [comment]
Hey, I figured I'd point you towards this document:

http://doc.manasource.org/hacking

I figure you could use this as a starting point for defining the coding style.

**Comment by Zardoz89** [comment]
Here is the "official" coding standards..... Feel free to  make changes : https://github.com/trillek-team/trillek-client-core/wiki/Coding-Standards
